'use client';

import Link from 'next/link';
import { Users, TrendingUp, Award, Headphones, ChevronRight } from 'lucide-react';

export default function BusinessPartnerPage() {
  const benefits = [
    {
      icon: Users,
      title: 'High Payouts',
      description: 'Earn up to 70% revenue sharing on brokerage generated by your clients'
    },
    {
      icon: TrendingUp,
      title: 'Zero Investment',
      description: 'Start your own franchise with zero initial investment or deposit'
    },
    {
      icon: Award,
      title: 'Brand Support',
      description: 'Leverage Ashlar India\'s 15+ years of trust and brand recognition'
    },
    {
      icon: Headphones,
      title: 'Dedicated Support',
      description: 'Get priority support for all your client-related queries'
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero */}
      <section className="relative bg-gradient-to-br from-[#1A1A2E] to-[#2D2D4A] py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Become Our Business Partner</h1>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            Grow your business with India's most trusted stockbroker
          </p>
        </div>
      </section>

      {/* Benefits */}
      <section className="py-16">
        <div className="max-w-6xl mx-auto px-4 sm:px-6">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-12">Partner Benefits</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {benefits.map((benefit, idx) => {
              const Icon = benefit.icon;
              return (
                <div key={idx} className="bg-white p-6 rounded-xl shadow-sm text-center">
                  <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <Icon size={24} className="text-blue-600" />
                  </div>
                  <h3 className="font-semibold text-gray-900 mb-2">{benefit.title}</h3>
                  <p className="text-sm text-gray-500">{benefit.description}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Ready to Partner with Us?</h2>
          <p className="text-gray-500 mb-6">Fill out our partner application form and we'll get back to you within 24 hours</p>
          <Link href="/contact" className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700">
            Apply Now <ChevronRight size={16} />
          </Link>
        </div>
      </section>
    </div>
  );
}